services:
  remnawave-tg-shop-db:
    image: postgres:17
    container_name: remnawave-tg-shop-db
    hostname: remnawave-tg-shop-db
    env_file:
      - .env
    volumes:
      - remnawave-tg-shop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  migrator:
    build: .
    container_name: remnawave-tg-shop-migrator
    hostname: remnawave-tg-shop-migrator
    env_file:
      - .env
    command: ["python", "-m", "scripts.migrator"]
    depends_on:
      remnawave-tg-shop-db:
        condition: service_healthy
    networks:
      - remnawave-network
    restart: "no"

  remnawave-tg-shop:
    build: .
    container_name: remnawave-tg-shop
    hostname: remnawave-tg-shop
    env_file:
      - .env
    networks:
      - remnawave-network
    volumes:
      - ./locales:/app/locales
    ports:
      - "${WEB_SERVER_PORT:-8080}:${WEB_SERVER_PORT:-8080}"
    restart: unless-stopped
    # ⬇️ Бот стартует ТОЛЬКО после успешного завершения мигратора
    depends_on:
      migrator:
        condition: service_completed_successfully

networks:
  remnawave-network:
    external: true

volumes:
  remnawave-tg-shop-db-data:
    name: remnawave-tg-shop-db-data
